services:
  postgres:
    image: paradedb/paradedb:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: medusa
    volumes:
      - ./data/paradedb_data:/var/lib/postgresql/
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1G'


volumes:
  paradedb_data: