packages:
  - "apps/*"
  - "packages/*"

packageExtensions:
  "@medusajs/medusa":
    dependencies:
      zod: 3.25.76

onlyBuiltDependencies:
  - "@medusajs/telemetry"
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - "@swc/core"
  - core-js
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver
